### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by severinEvo** [benedictpaten/pinchesAndCacti#9]
Hi!

I just tried to install pAC. I followed the instructions and cloned the project into /Library/Python/2.7/site-packages/pinchesAndCacti/. I had found sonLib (installed using pip) in /Library/Python/2.7/site-packages/sonLib/. It gives the error 

```
pinchesAndCacti severin$ sudo make all
cd externalTools && make all
cd threeEdgeConnected && /Library/Developer/CommandLineTools/usr/bin/make all
make[2]: *** No rule to make target `../..//../sonLib/lib/sonLib.a', needed by `../..//../sonLib/lib/3EdgeConnected.a'.  Stop.
make[1]: *** [all.threeEdgeConnected] Error 2
make: *** [externalToolsM] Error 2
```

I tried to uninstall sonLib through pip, clone it into place and install it that way, but that just causes an error for the sonLib install (below) and does not resolve the issue. Any ideas what to do? I'm on a macOS 10.13.5. Thanks a lot!

```
sonLib severin$ sudo make all
cd externalTools && make all
cd cutest && make all
clang -std=c99  -O3 -g -Wall --pedantic -funroll-loops -DNDEBUG  -c CuTest.c
ar rc cuTest.a *.o
ranlib cuTest.a
rm -f *.o
mv cuTest.a ../../lib/
cp CuTest.h ../../lib/
cd quicktree_1.1 && make all
gcc -c -I./include -O3 -Wall -o ./obj/align.o ./src/align.c
make[2]: *** [obj/align.o] Segmentation fault: 11
make[1]: *** [quicktreeM] Error 2
make: *** [externalToolsP] Error 2
```

**Comment by joelarmstrong** [comment]
Hi! You're right that installing sonLib through pip won't get you the compiled C library. (sonLib is sort of a weird hybrid of completely separate C/Python libraries in the same repository--a bad design but it sort of grew organically that way.)

You're on the right track by trying to compile sonLib, but your C compiler is crashing while trying to compile it. That usually means there's a compiler bug that we're somehow triggering. Can you paste in the output of `clang --version` and `gcc --version`?

**Comment by severinEvo** [comment]
Yeah, I sense a problem here, see below:

```
$ clang --version
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
$ gcc --version
Segmentation fault: 11
```

**Comment by joelarmstrong** [comment]
OK, if you pull sonLib and get [this commit](https://github.com/benedictpaten/sonLib/commit/e7ef98b0a719e13936bbde5598fbbeab155444a1), it should compile everything with one compiler rather than hardcoding gcc.

**Comment by severinEvo** [comment]
Thanks, that worked much better. Installation seemed to run (no errors or warnings thrown for what I can see), but `make test` still produces some errors. I can successfully install pAC now but the installation of mafTools returns errors. I'll first post the errors associated with sonLib:

`$ sudo make test`
[...]
```
======================================================================
ERROR: testFastaReadWriteC (bioioTest.TestCase)
Tests consistency with C version of this function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sonLib/bioioTest.py", line 185, in testFastaReadWriteC
    system(command)
  File "/Library/Python/2.7/site-packages/sonLib/bioio.py", line 185, in system
    raise RuntimeError("Command: %s exited with non-zero status %i" % (command, sts))
RuntimeError: Command: sonLib_fastaCTest /tmp/tmpc8BYYj /tmp/tmpPziwtQ exited with non-zero status 127

======================================================================
ERROR: testCigarReadWrite (cigarsTest.TestCase)
Tests the C code for reading and writing cigars against the python parser for cigars.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sonLib/cigarsTest.py", line 57, in testCigarReadWrite
    system(command)
  File "/Library/Python/2.7/site-packages/sonLib/bioio.py", line 185, in system
    raise RuntimeError("Command: %s exited with non-zero status %i" % (command, sts))
RuntimeError: Command: sonLib_cigarTest /tmp/tmpbaTcUC False exited with non-zero status 127

======================================================================
ERROR: testSonLibKVTokyoCabinet (kvdbTest.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sonLib/kvdbTest.py", line 18, in testSonLibKVTokyoCabinet
    system("sonLib_kvDatabaseTest --type=tokyocabinet")
  File "/Library/Python/2.7/site-packages/sonLib/bioio.py", line 185, in system
    raise RuntimeError("Command: %s exited with non-zero status %i" % (command, sts))
RuntimeError: Command: sonLib_kvDatabaseTest --type=tokyocabinet exited with non-zero status 127

======================================================================
ERROR: testSonLibCTests (__main__.TestCase)
Run m,ost the sonLib CuTests, fail if any of them fail.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "allTests.py", line 30, in testSonLibCTests
    system("sonLibTests %s" % getLogLevelString())
  File "/Library/Python/2.7/site-packages/sonLib/bioio.py", line 185, in system
    raise RuntimeError("Command: %s exited with non-zero status %i" % (command, sts))
RuntimeError: Command: sonLibTests CRITICAL exited with non-zero status 127

----------------------------------------------------------------------
Ran 19 tests in 1.956s

FAILED (errors=4)
make: *** [test] Error 4
```

I'm not sure if that causes why the mafTools installation. Here's the mafTools `make` error trace:

```
$ sudo make
cd lib && make all
gcc -O3 -c -std=c99 -O3 -Wextra -Wall -Werror -pedantic -I ../external/ -I ../inc/ common.c -o common.o.tmp
make[1]: *** [common.o] Segmentation fault: 11
make: *** [lib.all] Error 2
```
Thanks a lot for your help!

**Comment by joelarmstrong** [comment]
The sonLib `make test` error is because it (sort of stupidly) assumes the test binaries are in your PATH. So ``PATH=`pwd`/bin make test`` should hopefully work.

The mafTools error is because mafTools is trying to use your gcc installation again (and your gcc install seems to be broken). I could try to submit a PR to mafTools to switch to clang on macs, but I don't have direct commit access.

Maybe an easier workaround might be to try to redirect from the faulty gcc install to your correctly working clang install. The redirect would only be temporary. So something like this would hopefully work (from the mafTools directory):
```
ln -s `which clang` gcc
ln -s `which clang++` g++
PATH=`pwd`:$PATH sudo make
```
That creates a couple links in the local directory and the final line says to prefer those links over your actual gcc install for just the following command (`sudo make`).

**Comment by severinEvo** [comment]
Hi! Thanks for your help, much appreciated. Sorry, I just realized I should have closed this a while ago ... Cheers!
